name: Pre-Release
on:
  push:
    tags:
      - '*.*.*-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        python_version: '3.9'
        poetry_version: '==1.1.4'
        pypi_token: ${{ secrets.PYPI_TOKEN }}
