name: Release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  poetry_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        python_version: '3.9'
        poetry_version: '==1.1.4'
        pypi_token: ${{ secrets.PYPI_TOKEN }}

  docker_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag
        id: docker_build_with_tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: aidanmelen/website_checker:${{ steps.get_tag.outputs.TAG }}

      - name: Build and push latest
        id: docker_build_with_latest
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: aidanmelen/website_checker:latest

      - name: Image with tag digest
        run: echo ${{ steps.docker_build_with_tag.outputs.digest }}

      - name: Image with latest digest
        run: echo ${{ steps.docker_build_with_latest.outputs.digest }}
